#ifndef DEFS_H
#define DEFS_H


#define PHOTON_STR_APERTURE "Aperture"
#define PHOTON_STR_ISO      "ISO"
#define PHOTON_STR_SHUTTER_SPEED "Shutter speed"
#define PHOTON_STR_FOCAL_LENGTH "Focal lens"

#define PHOTON_NB_PLOT 4
#define PHOTON_ID_APERTURE      0
#define PHOTON_ID_ISO           1
#define PHOTON_ID_SHUTTER_SPEED 2
#define PHOTON_ID_FOCAL_LENGTH  3

#define PHOTON_PLOT_DIMENSION_X 800
#define PHOTON_PLOT_DIMENSION_Y 800

#define PHOTON_MAX_TAG_SIZE 1024
#define PHOTON_Y_AXIS_LABEL        "Times used"

#define PHOTON_ISO_LABEL           PHOTON_STR_ISO " speed"
#define PHOTON_SHUTTER_SPEED_LABEL PHOTON_STR_SHUTTER_SPEED " (s)"
#define PHOTON_APERTURE_LABEL      PHOTON_STR_APERTURE " (f)"
#define PHOTON_FOCAL_LENGTH_LABEL  PHOTON_STR_FOCAL_LENGTH " (mm)"

#define PHOTON_APERTURE_TITLE      PHOTON_STR_APERTURE " usage"
#define PHOTON_SHUTTER_SPEED_TITLE PHOTON_STR_SHUTTER_SPEED " usage"
#define PHOTON_ISO_TITLE           PHOTON_STR_ISO " usage"
#define PHOTON_FOCAL_LENGTH_TITLE  PHOTON_STR_FOCAL_LENGTH " usage"

#define PHOTON_X_LABEL_ROTATION (-60)

#endif // DEFS_H
